<?php 
/** Ofuz Open Source version is released under the GNU Affero General Public License, please read the full license at: http://www.gnu.org/licenses/agpl-3.0.html **/ 
// Copyright 2008 - 2010 all rights reserved, SQLFusion LLC, info@sqlfusion.com
/** Ofuz Open Source version is released under the GNU Affero General Public License, please read the full license at: http://www.gnu.org/licenses/agpl-3.0.html **/

 /** Generated by the manageIncludes Event **/

  

   $pageTitle = "Page Title";
   $Author = "PAS Pagebuilder";
   $Keywords = "PAS Pagebuilder SQLFusion Web authoring tool";
   $Description = "The best way to built rich web sites";
   $background_color = "white";
   $background_image = "none";
   include_once("config.php");
   include_once("includes/onlyloginusers.script.inc.php");
   include_once("includes/header.inc.php");
?>
<DIV id="DRAG_addon_LogoutAddOn" style="top:43px;left:499px;height:39px;width:125px;position:absolute;visibility:visible;z-index:5;border-style:none;">
<!--META  metainfo="execorder:30;classname:LogoutAddOn;filename:class/;notdragable:no;global:no;" --><?php if($_GET['message']) { ?><div class="error_message"><?php echo htmlentities(stripslashes($_GET['message'])); ?></div>
<?php }?>
<?php $do_user = new User();
 $do_logout = new Event("do_User->eventLogout"); 
 $do_logout->addParam("goto","index.php"); 
 $do_logout->addParam("full_sign_off",""); 
 echo $do_logout->getLink("Sign-out"); 
?>
</DIV>


<DIV id="DRAG_script_persoWelcome" style="top:46px;left:41px;height:33px;width:441px;position:absolute;visibility:visible;" class="Heading1">
<!--META  metainfo="filename:includes/blank_script.script.inc.php;" -->Welcome <?php
  $q_user = new sqlQuery($GLOBALS['conx']);
  $q_user->query("select * from users where idusers=".$_SESSION['userdata']['id']);
  $q_user->fetch();
  
  echo $q_user->getData("firstname")."  ".$q_user->getData("lastname");

?>
</DIV>


<DIV id="DRAG_txt_Unnamed" style="top:116px;left:138px;height:98px;width:394px;position:absolute;visibility:visible;z-index:5;" class="text">
<!--META  metainfo="execorder:30;" -->This is the registered users landing page.<br />
It can only be viewed by the registered users.<br />
<br />
We have added to this page a welcome script that contain some PHP to retrieve and display the sign in user's first name and last name.<br />
<br />
We have also added a sign off link that you can reuse is you members page.
</DIV>



  </body>
</html>