ALTER TABLE `activity` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `breadcrumb` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `company` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `company_address` CHANGE COLUMN `address_type` `address_type` varchar(10) CHARACTER SET ucs2 NOT NULL; # was varchar(10) NOT NULL
ALTER TABLE `company_address` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `company_email` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `company_phone` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `company_website` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_email` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_instant_message` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_note` ADD COLUMN `type` varchar(100) NOT NULL;
ALTER TABLE `contact_phone` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_rss_feed` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_sharing` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `contact_website` CHANGE COLUMN `feed_auto_fetch` `feed_auto_fetch` varchar(5) CHARACTER SET ucs2 NOT NULL DEFAULT 'None'; # was varchar(5) NOT NULL DEFAULT 'None'
ALTER TABLE `contact_website` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `countries` ENGINE=MyISAM AUTO_INCREMENT=253 DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=253 DEFAULT CHARSET=latin1
ALTER TABLE `created_date_log` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `discussion_email_setting` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `emailtemplate` ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=latin1
ALTER TABLE `emailtemplate_user` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `google_account` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `google_contact` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `google_contact_info` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `message` ENGINE=MyISAM AUTO_INCREMENT=80 DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=61 DEFAULT CHARSET=latin1
ALTER TABLE `note_draft` CHANGE COLUMN `note_content` `note_content` text NOT NULL; # was text CHARACTER SET utf8 NOT NULL
ALTER TABLE `note_draft` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `payment_invoice` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `payments` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `project` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `project_discuss` ADD COLUMN `type` varchar(100) NOT NULL;
ALTER TABLE `project_sharing` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `project_task` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `states` CHANGE COLUMN `name` `name` text CHARACTER SET latin1 NOT NULL; # was text NOT NULL
ALTER TABLE `states` ENGINE=MyISAM AUTO_INCREMENT=1011522957 DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=1011522957 DEFAULT CHARSET=latin1
ALTER TABLE `tag` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `tag_association` CHANGE COLUMN `iduser` `iduser` varchar(16) CHARACTER SET utf8 COLLATE utf8_latvian_ci NOT NULL; # was varchar(16) NOT NULL
ALTER TABLE `tag_association` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `tag_click` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `tag_size` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `task` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `task_category` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `temp_gmail_emails` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `temp_import` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `updated_date_log` ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='record all updated records'; # was ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='record all updated records'
ALTER TABLE `user` ADD COLUMN `google_openid_identity` varchar(250) NOT NULL;
ALTER TABLE `user_relations` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `webformfields` ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1
ALTER TABLE `webformuser` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `webformuserfield` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1
ALTER TABLE `workfeed` ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE `message_usage` (
  `idmessage_usage` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `date_sent` date NOT NULL DEFAULT '0000-00-00',
  `num_msg_sent` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idmessage_usage`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

CREATE TABLE `plugin_enable` (
  `idplugin_enable` int(10) NOT NULL AUTO_INCREMENT,
  `plugin` varchar(200) NOT NULL,
  `enabled` int(1) NOT NULL,
  `iduser` varchar(19) NOT NULL,
  `date_modified` datetime NOT NULL,
  PRIMARY KEY (`idplugin_enable`),
  UNIQUE KEY `idplugin_enable_2` (`idplugin_enable`),
  KEY `idplugin_enable` (`idplugin_enable`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

